version: "3.8"

networks:
  app-network:

volumes:
  mongo-data:

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  backend:
    build: ./server
    ports:
      - "7500:7500"
    volumes:
      - ./server:/app
    env_file:
      - .env.local
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  reddit_service:
    build:
      context: ./server/reddit_service
      dockerfile: Dockerfile
    ports:
      - "5008:5008"
    env_file:
      - ./server/reddit_service/.env.local
    command: ["python", "app.py"]
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  storage_service:
    build:
      context: ./server/storage_service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    env_file:
      - ./server/storage_service/.env.local
    command: ["python", "app.py"]
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  sentiment_service:
    build:
      context: ./server/sentiment_service
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    env_file:
      - ./server/sentiment_service/.env.local
    command: ["python", "app.py"]
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
