name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Backend setup (runner Python version doesn't need to match EB's runtime)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install backend dependencies
        run: |
          cd server
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # DockerHub Authentication Step (kept if you still want images on DockerHub)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build and Push Backend Image to DockerHub (optional for EB Python platform)
      - name: Build and Push Backend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/reddit-sentiment-backend:latest ./server
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/reddit-sentiment-backend:latest

      # Create a New Application Version (AWS CLI)
      - name: Create a New Application Version
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-north-1"
        run: |
          cd server
          VERSION_LABEL="app-version-${{ github.run_id }}"
          KEY="deployments/${VERSION_LABEL}.zip"

          # Create a zip from ./server (Procfile must be in this folder)
          zip -r "../${VERSION_LABEL}.zip" . -x "venv/*" ".git/*" ".github/*" "*.DS_Store" "tests/*"
          unzip -l "../${VERSION_LABEL}.zip" | sed -n '1,200p'

          # Upload to S3 (unique key per run)
          aws s3 cp "../${VERSION_LABEL}.zip" "s3://elasticbeanstalk-eu-north-1-600627335166/${KEY}"

          # Create EB application version (app name must match console)
          aws elasticbeanstalk create-application-version \
            --application-name "Reddit_Sentiment_Analysis_Project" \
            --version-label "${VERSION_LABEL}" \
            --source-bundle S3Bucket="elasticbeanstalk-eu-north-1-600627335166",S3Key="${KEY}" \
            --region "$AWS_REGION"

      # Deploy that version to the **new** environment
      - name: Deploy Backend to AWS Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-north-1"
        run: |
          VERSION_LABEL="app-version-${{ github.run_id }}"

          # Point the environment to the new version
          aws elasticbeanstalk update-environment \
            --environment-name "RedditSentimentAnalysisProject-env-3" \
            --version-label "${VERSION_LABEL}" \
            --region "$AWS_REGION"

          # (Optional) Wait until the deployment finishes
          aws elasticbeanstalk wait environment-updated \
            --environment-names "RedditSentimentAnalysisProject-env-3" \
            --region "$AWS_REGION"
