name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Backend setup
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install backend dependencies
        run: |
          cd server
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # DockerHub Authentication Step (For Backend)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build and Push Backend Docker Image
      - name: Build and Push Backend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/reddit-sentiment-backend:latest ./server
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/reddit-sentiment-backend:latest

      # Check if Application Environment Exists
      - name: Check if Application Environment Exists
        id: check_env
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-north-1"
        run: |
          if aws elasticbeanstalk describe-environments --environment-names RedditSentimentAnalysisProject-env-1 --region $AWS_REGION --no-cli-pager; then
            echo "env_exists=true" >> $GITHUB_ENV
          else
            echo "env_exists=false" >> $GITHUB_ENV
          fi

      # Install the AWS EB CLI
      - name: Install AWS EB CLI
        run: |
          pip install awsebcli

      # Initialize Elastic Beanstalk Environment (only needed for first-time setup)
      - name: Initialize EB Environment
        if: ${{ env.env_exists == 'false' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-north-1"
        run: |
          cd server
          eb init RedditSentimentAnalysisProject --platform "Python 3.9" --region $AWS_REGION 

      # Deploy or Create Application
      - name: Deploy or Create Application
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-north-1"
        run: |
          cd server
          if [ "$env_exists" = "true" ]; then
            eb deploy RedditSentimentAnalysisProject-env-1 --label "app-version-${{ github.run_id }}" --staged
          else
            echo "Skipping eb create since the environment already exists."
          fi
